version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: caravan-store-caravan_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  web:
    build:
      context: https://github.com/AlexM223/caravan.git#umbrel
      dockerfile: apps/coordinator/Dockerfile.umbrel
    restart: on-failure
    environment:
      BITCOIND_HOST: $APP_BITCOIN_NODE_IP
      BITCOIND_PORT: $APP_BITCOIN_RPC_PORT
      BITCOIND_USER: $APP_BITCOIN_RPC_USER
      BITCOIND_PASS: $APP_BITCOIN_RPC_PASS
      BITCOIND_NETWORK: $APP_BITCOIN_NETWORK
